version: '3'
services:
  app:
    build:
      args:
        user: appuser
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: url-shortener
    container_name: url-shortener-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - url-shortener

  nginx:
    image: nginx:1.25-alpine
    container_name: url-shortener-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - url-shortener

  mysql:
    image: mysql:8.0
    container_name: url-shortener-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    networks:
      - url-shortener

  redis:
    image: redis:alpine
    container_name: url-shortener-redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - url-shortener

networks:
  url-shortener:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local